RedHatInsights/insights-frontend

app/js/api/rule.js, app/js/components/actions/actionsRule/actionsRule.controller.js, app/js/components/actions/actionsRule/actionsRule.jade, app/js/components/card/systemCard/systemCard.directive.js, app/js/components/card/systemCard/systemCard.jade, app/js/components/inventory/inventoryActions/inventoryActions.directive.js, app/js/components/maintenance/maintenanceModal/maintenanceModal.directive.js, app/js/components/maintenance/maintenanceModal/maintenanceModal.jade, app/js/components/maintenance/maintenancePlan/maintenancePlan.directive.js, app/js/components/maintenance/maintenancePlan/maintenancePlan.jade, app/js/components/maintenance/maintenanceTable/maintenanceTable.controller.js, app/js/components/maintenance/maintenanceTable/maintenanceTableMulti.jade, app/js/components/overview/widgets/maintenancePlanLite/maintenancePlanLite.jade, app/js/services/maintenance.service.js, app/js/states/inventory/inventory.jade, app/js/states/maintenance/maintenance.controller.js, app/js/states/maintenance/maintenance.jade, app/styles/components/maintenance-planner/_maintenance-plan.scss, test/unit/states/maintenance/category_spec.js
https://trello.com/c/eTroW2g4/110-rework-how-we-do-add-to-plan-in-planner
=> revisit planner modal and how actions are added to plans

app/js/states/topics/controllers/edit.topics.controller.js, app/js/states/topics/views/edit-topics.jade, app/js/states/topics/views/topic-admin.jade
https://trello.com/c/3aZu6llG/5-granular-control-over-which-topics-are-shown-in-the-topic-list
=> topics - granular control over which topics are listed

app/js/states/splash/splash.jade
=> Update copy per issue 101

app/js/states/splash/splash.jade
* [splash] Update copy per issue 101
* [splash] removing email link
=> Update copy per issue 101 (#102)

app/js/components/ansibleIcon/ansibleIcon.jade, app/js/components/maintenance/maintenanceTable/maintenanceTableMulti.jade, app/js/components/overview/widgets/maintenancePlanLite/maintenancePlanLite.jade
https://github.com/RedHatInsights/insights-frontend/issues/100
https://trello.com/c/Tw1LEhHO/113-review-ansible-icon-tooltips
=> ansible-icon improvements

app/js/states/overview/overview.jade
https://github.com/RedHatInsights/insights-frontend/issues/105
=> #105 planner-lite not respecting isPlannerEnabled flag

app/js/states/inventory/inventory.jade
Fix for Sat table @ Lindani's request
=> Adding table class to inventory table

app/js/components/announcements/announcementsScroll/announcementsScroll.directive.js, app/js/components/config/permissions/permissions.directive.js, app/js/components/group/group.directive.js, app/js/components/inventory/inventoryActions/inventoryActions.directive.js, app/js/components/maintenance/maintenancePlan/maintenancePlan.directive.js, app/js/components/maintenance/maintenanceTable/maintenanceTable.controller.js, app/js/components/system/systemSummaryTable/systemSummaryTable.directive.js, app/js/services/sweetalert.service.js, app/js/services/systems.service.js, app/js/states/topics/controllers/topic.admin.controller.js, app/styles/base.scss, app/styles/components/_inventory.scss, bower.json
This is needed for the upcoming group management UI.
besides the component upgrade this change also:
- switches to using promises for alert confirmation/dismiss
- removes some dead code
- removes code duplication
=> replace SweetAlert with SweetAlert 2

app/js/components/maintenance/maintenanceModal/maintenanceModal.directive.js
Fix for https://github.com/RedHatInsights/insights-frontend/issues/114
=> #114 system missing from add specific system search results in planner

app/js/states/digests/digests.controller.js, app/js/states/digests/digests.jade
=> Changing digest systems string #124

app/js/components/actions/actionsRule/actionsRule.controller.js, app/js/services/inventory.service.js
=> obey showsystem configuration

app/js/states/splash/splash.jade
=> [goof] there were some references to static/static in splash.jade

app/js/states/rules/list-rules.jade, app/styles/components/_content-block.scss
=> updated bg-color/padding on knowledgebase link #133

app/js/components/actions/severitySummary/severitySummary.jade
Icon colors are changed to green. Fixes issue #143
=> Changed color of check icons

app/js/components/topbar/topbar.jade, app/styles/components/_dropdown.scss
=> Adding li elements to ul

app/js/components/overview/widgets/goals/goalsLite.jade, app/styles/page-templates/_goals-lite.scss
Issue #93 
Took out the second spinner. Added styling to make the spinner full width and added the "loading" text.
=> Fixed Issue #93

app/js/components/topics/topicRuleList/topicRuleList.directive.js, app/js/components/topics/topicRuleList/topicRuleList.jade, app/styles/components/_icons.scss
Changed jade logic, added some js to expose, and added styles to format correctly. #149
=> Fixes/actions bullseye icon. Fixes issue #149

app/js/components/overview/widgets/goals/goalsLite.directive.js, app/js/components/overview/widgets/goals/goalsLite.jade
Fixes #91 
Also cleans up the loading code a bit.
=> Removes unpaginated calls to reports and systems in favor of stats calls

.gitignore, .gitmodules, .travis.yml, README.md
We can do this now that the assets are all under static/
See the updated README.md for tips.
=> Add the static assets as a Git submodule.

app/styles/components/_beta-switch.scss, app/styles/elements/_base.scss
Changed a few z-indexes around. The utility bar on the top should be active over everything until a modal is opened. Fixes #171
=> Changed z-indexes, allows modal to open over everything.

app/js/components/ansibleIcon/ansibleIcon.directive.js, app/js/components/ansibleIcon/ansibleIcon.jade, app/js/components/maintenance/expandableSystemList/expandableSystemList.jade, app/js/components/maintenance/expandableSystemList/expandableSystemList.js, app/js/components/maintenance/maintenanceModal/maintenanceModal.jade, app/js/components/maintenance/maintenancePlan/maintenancePlan.directive.js, app/js/components/maintenance/maintenancePlan/maintenancePlan.jade, app/js/components/maintenance/resolutionModal/resolutionModal.jade, app/js/routes.js, app/js/states/maintenance/maintenance.controller.js, app/styles/base.scss, app/styles/components/_icons.scss, app/styles/components/_pager.scss, app/styles/components/maintenance-planner/_maintenance-plan.scss, app/styles/components/utilities/_toggle-slider.scss, app/styles/elements/_buttons.scss, app/styles/elements/_tabs.scss
=> planner - system reboot handling

smoketest/suites/planner.js
it intermittently fails to clean up the created plan which polutes 540155
=> disable planner smoke test for now

app/js/routes.js, app/js/services/inventory.service.js, app/js/states/actions/actions.controller.js, app/js/states/inventory/inventory.controller.js, app/js/states/inventory/inventory.jade
Replaces infinite scroll with pagination.
- Removed InventoryService from actions.controller.js because it was not being used.
- Removed paginate variables from InventoryService and used pager util
- Set default size to 10 to minimize scrolling and make moving through pages fast
=> adds pagination to inventory page

app/js/states/rules/list-rules.jade, app/js/states/rules/list.rules.controller.js
Fixes search on the rules page.
=> fixes rules page search

app/js/components/actions/actionsRule/actionsRule.jade, app/js/states/inventory/inventory.jade, app/js/states/maintenance/maintenance.jade, app/js/states/rules/list-rules.jade, app/js/states/topics/views/topic-list.jade
https://github.com/RedHatInsights/insights-frontend/issues/202
=> additional search guidance on search boxes

app/js/components/actions/actionsRule/actionsRule.jade, app/js/components/pageHeader/pageHeader.directive.js, app/js/components/pageHeader/pageHeader.jade, app/js/states/actions/actions.jade, app/js/states/config/views/config.jade, app/js/states/digests/digests.jade, app/js/states/inventory/inventory.jade, app/js/states/maintenance/maintenance.jade, app/js/states/overview/overview.jade, app/js/states/rules/list-rules.jade, app/js/states/topics/views/topic-list.jade, app/styles/components/_page-header.scss, app/styles/components/maintenance-planner/_maintenance-plan.scss
Please dont merge until the `Planner` page is fixed.
There is some incompatibility that needs to be resolved there first.
=> [pageHeader] Introduce component so that we dont copypasta the pageHeader

app/js/components/inventory/inventoryActions/inventoryActions.jade, app/js/states/inventory/inventory.controller.js
Allows user to select systems from current page as well.
Allows user to select all systems after selecting all systems on the current page.
#198
=> Add really select all back into inventory for pagination

app/js/components/groupSelect/groupSelect.directive.js, app/js/components/groupSelect/groupSelect.jade, app/styles/components/insights/_group-select.scss
=> Fixed global filter delete function

app/js/states/digests/digests.jade
There's also a double negative in the tooltip verbiage..
=> Updating score verbiage

app/js/api/webhooks.js, app/js/components/config/webhooks/webhooks.directive.js, app/js/components/config/webhooks/webhooks.jade, app/js/states/config/views/config.jade
https://github.com/RedHatInsights/insights-api/issues/1
=> webhook management UI

app/js/states/rules/list-rules.jade
=> adds a no results message to rules

app/js/components/incidentSummary/incidentSummary.directive.js, app/js/services/incidents.service.js, app/js/states/actions/actions.controller.js
=> fixes issue count for incident summary

app/js/components/overview/widgets/goals/goalsLite.directive.js, app/js/components/overview/widgets/goals/goalsLite.jade
Couldn't force push to stable-4.10 sooooo......PR
=> fixes overview goals widget counts and links

app/js/api/ack.js, app/js/components/filterComponents/ansibleSupportTriState/ansibleSupportTriState.controller.js, app/js/components/filterComponents/ansibleSupportTriState/ansibleSupportTriState.jade, app/js/components/filterComponents/impactSelect/impactSelect.directive.js, app/js/components/filterComponents/impactSelect/impactSelect.jade, app/js/components/filterComponents/incidentsTriState/incidentsTriState.controller.js, app/js/components/filterComponents/likelihoodSelect/likelihoodSelect.directive.js, app/js/components/filterComponents/likelihoodSelect/likelihoodSelect.jade, app/js/components/filterComponents/ruleStatusTriState/ruleStatusTriState.controller.js, app/js/components/filterComponents/ruleStatusTriState/ruleStatusTriState.jade, app/js/components/filterComponents/totalRiskSelect/totalRiskSelect.controller.js, app/js/components/rule/ruleFilter/ruleFilter.jade, app/js/constants/events.js, app/js/constants/filters.js, app/js/services/filter.service.js, app/js/states/rules/list-rules.jade, app/js/states/rules/list.rules.controller.js
This is for issue #176 and #154
=> New rules page filters

app/js/constants/events.js, app/js/routes.js
I changed app/js/constants/events.js to only change the construction of the filters because I did not know if any of the other files used the "filter:event" formatting
=> Add queries to routes

app/styles/components/_actionbar.scss, app/styles/components/maintenance-planner/_maintenance-plan.scss
Now these buttons have consistent padding with other buttons on the site
#266
=> Removed specific padding for action buttons

app/js/constants/constants.js, app/js/portal/routes.js
=> routes invite to RH eval form

app/js/components/maintenance/maintenanceModal/maintenanceModal.directive.js
https://github.com/RedHatInsights/insights-frontend/issues/246
=> #246 Planner auto selects a group for default view vs select all

app/js/states/rules/list-rules.jade, app/js/states/rules/list.rules.controller.js
=> Adding client side pagination to stop the slow

app/js/components/rule/ruleFilter/ruleFilter.jade, app/js/constants/filters.js
=> hides ansible filter when planner disabled; relabels rule status values

app/js/components/systemMetadata/systemMetadata.directive.js, app/js/components/systemMetadata/systemMetadata.jade, app/styles/components/system-overlay/_system-metadata.scss, app/styles/components/system-overlay/_system-overlay.scss
Should fix the errors found in #289
=> Fixed system modal alignment

app/js/components/filterComponents/ageSelect/ageSelect.directive.js, app/js/components/filterComponents/ageSelect/ageSelect.jade, app/js/components/filterComponents/impactSelect/impactSelect.directive.js, app/js/components/filterComponents/ruleStatusTriState/ruleStatusTriState.jade, app/js/components/rule/ruleFilter/ruleFilter.jade, app/js/constants/events.js, app/js/routes.js, app/js/services/filter.service.js
First part of frontend change for #284
=> Filter rules by age first part of #284

app/js/states/digests/digests.jade
User must have 10 or more systems for button to appear #288
=> Added logic to show download pdf button

app/js/components/filterComponents/ageSelect/ageSelect.directive.js, app/js/components/overview/widgets/newRules/newRules.directive.js, app/js/components/overview/widgets/newRules/newRules.jade, app/js/routes.js, app/js/services/filter.service.js, app/js/services/permalink.service.js, app/js/states/overview/overview.jade, app/js/states/rules/list-rules.jade, app/js/states/rules/list.rules.controller.js, app/styles/base.scss, app/styles/components/_newRules.scss
This is the second part for #284 
One very notable thing here is that mid development I noticed that hash params are broken in Insights.
For this PR I worked around the issue (#293).
I would like to solve #293 in another PR.
=> Features/newest rules overview #284 part two

app/js/api/system.js, app/js/components/system/systemModal/systemModal.controller.js, app/js/components/system/systemModal/systemModal.jade, app/js/components/systemMetadata/systemMetadata.directive.js, app/js/components/systemMetadata/systemMetadata.jade, app/js/services/modalUtils.js, app/styles/components/system-overlay/_system-metadata.scss
https://github.com/RedHatInsights/insights-frontend/issues/163
=> make it possible to rename a system

README.md
Just installed fresh fedora -  I needed a c++ compiler to gem install compass.
=> Update readme - specify more dependencies

app/js/components/maintenance/maintenanceModal/maintenanceModal.directive.js, app/js/components/maintenance/maintenanceModal/maintenanceModal.jade, app/js/components/systemMetadata/systemMetadata.directive.js, app/js/components/systemMetadata/systemMetadata.jade, app/js/components/topbar/topbar.directive.js, app/js/components/topbar/topbar.jade, app/js/providers/config.provider.js
enabled by default, use InsightsConfigProvider.setGroupsEnabled(false) to disable
=> add a switch to enable/disable groups

app/js/services/actions.service.js
=> Fixed search bar functionality in actions service

app/js/components/filterComponents/actionsSelect/actionsSelect.directive.js, app/js/components/maintenance/maintenanceCategorySelect/maintenanceCategorySelect.directive.js, app/js/routes.js, app/js/services/filter.service.js, app/js/states/maintenance/maintenance.controller.js, app/js/states/maintenance/maintenance.jade
=> Filters persist on page reload for plans/system health

app/js/constants/products.js
=> changes RHEV to RHV to match product direction

app/js/components/system/systemModal/systemModal.jade
=> Removed extra system not checking bar

app/js/states/overview/overview.controller.js
=> Looks like the isInternal var used to be set for the view, restoring

app/js/components/rule/ruleSummary/ruleSummary.jade
=> Changed modal from left/right split to top/bottom

app/js/components/filterComponents/searchBox/searchBox.directive.js, app/js/components/filterComponents/searchBox/searchBox.jade, app/js/services/filter.service.js, app/js/states/inventory/inventory.controller.js
fixes #323 
**Before reload**
**After reload**
=> Search term stays in the search bar when refreshing the page

app/js/components/riskOfChange/_risk-of-change.scss
=> Fixed Risk of Change "very low" wrapping two lines

app/js/components/actions/actionsRule/actionsRule.jade, app/js/components/betaSwitchButton/betaSwitchButton.jade, app/js/components/card/systemCard/systemCard.jade, app/js/states/inventory/inventory.jade
=> Added aria labels to checkboxes to fix label warnings

app/js/components/ansibleIcon/_ansible-icon.scss, app/js/components/filters/filters.js, app/js/components/maintenance/maintenanceTable/maintenanceTableMulti.jade, app/js/components/rule/ruleGroupCard/ruleGroupCard.jade, app/js/components/rule/ruleSummaries/ruleSummaries.jade, app/js/states/actions/actions.jade, app/js/states/topics/views/topic-list.jade, app/styles/components/_announcements.scss, app/styles/components/_card.scss, app/styles/components/_pager.scss, app/styles/components/_tables.scss, app/styles/components/insights/_notifications.scss, app/styles/page-templates/_actions.scss
=> Fixing more unportal bugs

app/js/states/base/app.jade
=> Plans do not close when clicking topbar

app/js/components/betaSwitchButton/betaSwitchButton.jade, app/js/components/topbar/topbar.jade, app/styles/components/_beta-switch.scss, app/styles/components/maintenance-planner/_maintenance-plan.scss
As of now fixes:
Beta button checkbox
Planner modal inputs
Help menu links
=> More unportal bug fixes

app/js/components/actions/actionsRule/actionsRule.jade, app/js/components/system/systemModal/systemModal.controller.js
=> Added esc navigation to actions rule page

app/js/insights.js, app/js/portal/boot.js
=> Do not bootstrap in the Portal until after the JWT session code has run #371

app/js/components/maintenance/maintenancePlan/maintenancePlan.jade, app/js/services/maintenance.service.js
fixes https://github.com/RedHatInsights/insights-frontend/issues/370
=> fix planner regressions

app/js/components/betaSwitchButton/betaSwitchButton.jade
=> Only show 'beta options' when in beta

app/js/components/maintenance/resolutionModal/resolutionModal.jade, app/styles/components/maintenance-planner/_maintenance-plan.scss
=> Changed button styles on resolution modal

app/js/components/betaSwitchButton/betaSwitchButton.jade, app/js/components/filterComponents/actionsSelect/actionsSelect.jade, app/js/components/filterComponents/checkInSelect/checkInSelect.directive.js, app/js/components/maintenance/maintenancePlan/maintenancePlan.jade, app/js/components/maintenance/resolutionModal/resolutionModal.jade, app/js/components/primary-nav/primary-nav.jade, app/js/insights.js, app/js/portal/boot.js, app/js/services/maintenance.service.js, app/js/states/policies/controllers/view.policy.controller.js, app/js/states/policies/views/view-policy.jade, app/styles/components/maintenance-planner/_maintenance-plan.scss, app/styles/includes/_mixins.scss, app/styles/includes/_vars.scss, app/styles/page-templates/_policies.scss
I am backporting all recent bug fixes from master (planner, policies, beta options, jwt).
=> backport recent bug fixes to stable

app/js/components/systemMetadata/systemMetadata.directive.js, app/js/components/systemMetadata/systemMetadata.jade, app/js/components/toasts/undoDeleteWithClose.jade, app/js/components/viewSystemGroups/viewSystemGroups.jade, app/styles/base.scss, app/styles/components/_policies-modal.scss, app/styles/components/_with-tile.scss, app/styles/components/insights/_alert.scss, app/styles/components/system-overlay/_system-metadata.scss, app/styles/components/system-overlay/_system-overlay.scss, app/styles/components/system-overlay/_view-system-groups.scss, app/styles/components/utilities/_expandable-data-table.scss, app/styles/includes/_colors.scss, app/styles/includes/_mixins.scss
=> New system modal design

app/js/components/incident/incidentLite/incidentLite.directive.js, app/js/components/incident/incidentLite/incidentLite.jade, app/js/components/rule/ruleSummaries/ruleSummaries.directive.js, app/js/states/actions/actions.controller.js, app/js/states/digests/digests.controller.js, app/styles/components/maintenance-planner/_maintenance-plan.scss
* rule name in maintenanceTableActions should not take up the entire cell
* use toString instead of hostname, localize loading message
* system modal - show reports in descending severity order
* remove unused API call
=> minor fixes

app/js/components/riskOfChange/_risk-of-change.scss, app/js/components/rule/ruleSummary/_rule-summary.scss, app/js/components/rule/ruleSummary/ruleSummary.jade, app/styles/components/_card.scss, app/styles/components/system-overlay/_system-overlay.scss
@iphands This should take care of the icons in titles
=> Removing severities from title

app/js/components/primary-nav/primary-nav.directive.js
so that I can use policies on my own systems
=> enable policies for 901578

app/js/components/filterComponents/searchBox/searchBox.jade
=> fixed search bar icon showing up as opposite icon

app/js/components/actions/actionsRule/actionsRule.controller.js
=> fixed cannot read property error thrown by actions rule page

app/js/components/systemMetadata/systemMetadata.directive.js, app/js/components/systemMetadata/systemMetadata.jade
=> Fixed ng-repeat dupes and tableData variable used for tabs

app/styles/elements/_buttons.scss
=> Increasing contrast of dropdowns

app/js/components/groupSelect/groupSelect.directive.js, app/js/services/utils.service.js
This addresses https://bugzilla.redhat.com/show_bug.cgi?id=1541063
Should be on Alpha soon https://access.redhat.com/insightsalpha/overview/
@Robcwilliams ^
=> Stash group selection in local storage and restore it on app launch

app/js/components/filterComponents/searchBox/searchBox.directive.js, app/js/routes.js
=> search bar field not reused when switching pages

app/js/components/maintenance/maintenancePlan/maintenancePlan.directive.js, app/js/components/maintenance/maintenancePlan/maintenancePlan.jade, app/js/portal/config.js, app/js/providers/config.provider.js, app/styles/elements/_buttons.scss
Just backporting this from master https://github.com/RedHatInsights/insights-frontend/pull/398
=> add Ansible Playbook runner controls for Satellite

app/js/components/groupSelect/groupSelect.directive.js, app/js/services/account.service.js
=> groupSelect - do not try to restore group if I am on a different account

app/js/routes.js
=> added search_term to routes.js

app/js/api/webhooks.js, app/js/states/config/views/webhook-edit.jade, app/js/states/config/webhook-edit.controller.js, app/js/states/config/webhook-edit.scss
https://github.com/RedHatInsights/insights-frontend/issues/354
=> webhooks - make it possible to limit to a given system group

app/js/components/maintenance/maintenancePlan/maintenancePlan.jade, app/styles/components/maintenance-planner/_maintenance-plan.scss
=> Fixing planner ui split 

package.json
An attempt to fix the full reload.
=> Upgrade jwt-redhat package

app/js/components/filterComponents/daysKnownSelect/daysKnownSelect.directive.js, app/js/components/renameableProperty/renameableProperty.jade, app/js/components/systemMetadata/systemMetadata.jade, app/js/components/vulnerabilities/erratumCard/erratumCard.jade, app/js/components/vulnerabilities/vulnerabilities-modal/vulnerabilities-modal.directive.js, app/js/components/vulnerabilities/vulnerabilities-modal/vulnerabilities-modal.jade, app/js/constants/filters.js, app/js/states/vulnerabilities/controllers/view.cve.controller.js, app/js/states/vulnerabilities/controllers/view.erratum.controller.js, app/js/states/vulnerabilities/controllers/vulnerabilities.controller.js, app/js/states/vulnerabilities/views/view-cve.jade, app/js/states/vulnerabilities/views/vulnerabilities.jade, app/styles/components/_renameable-property.scss, app/styles/elements/_lists.scss, smoketest/elements.js, smoketest/insightsTest.js
closes https://github.com/RedHatInsights/insights-frontend/issues/461
=> minor VMaaS fixes (2)

app/js/states/evaluation/evaluation.jade, app/styles/components/_loader.scss
Small fix.  Didn't catch it the first time around.
=> Spinner on new eval page can't been seen, updating colors

app/js/components/topics/topicDetails/_topicDetails.scss, app/js/states/topics/styles/_topic-admin.scss, app/js/states/topics/views/edit-topics.jade, app/js/states/topics/views/topic-admin.jade, app/styles/components/_icons.scss, app/styles/elements/_buttons.scss
=> Updating topic-admin pages with new styles

app/js/states/maintenance/maintenance.controller.js
as internal user hit the DELETE key 7 times on /maintenance to activate
=> planner - introduce hidden "delete all plans" feature

app/js/api/export.js, app/js/components/primary-nav/primary-nav.jade, app/js/components/system/systemModal/systemModal.jade, app/js/states/inventory/inventory.jade, app/js/states/overview/overview.jade, smoketest/elements.js
this deploys VMaaS UI support to all accounts
=> enable VMaaS UI for everyone

app/po/ja/ja.po
=> Add new ja.po file

app/js/api/export.js, app/js/components/primary-nav/primary-nav.jade, app/js/components/system/systemModal/systemModal.jade, app/js/states/inventory/inventory.jade, app/js/states/overview/overview.jade
This reverts commit 2de7dd4389528e2407550c8c1aae840eac5f2423.
=> Revert "enable VMaaS UI for everyone"

app/js/components/rule/ruleSummary/ruleSummary.jade
this change reverts a small part of https://github.com/RedHatInsights/insights-frontend/commit/d741fc61368a42da2afb33703c9323f75ae7e92a#diff-3bb0b593a8526fde55ab111b7ae3a95b
fixes https://github.com/RedHatInsights/insights-frontend/issues/492
=> fix ruleSimmary regression #492

app/js/components/rule/ruleSummary/ruleSummary.jade
this change reverts a small part of https://github.com/RedHatInsights/insights-frontend/commit/d741fc61368a42da2afb33703c9323f75ae7e92a#diff-3bb0b593a8526fde55ab111b7ae3a95b
=> fix ruleSimmary regression #492 (#493)

package.json
Dan can you test and ack.
WFM though.
=> Switch to hotfix version of jwt-redhat fork

.travis.yml, deploy.sh
Migrate to travis for building and deploying the insights-frontend
=> Travis pipeline
